# Generated by Django 6.0.7 on 2026-07-13 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('done', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(default='alibaba', max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contato_extraido', 'Contato extraído'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='novo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('platform', 'name', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('promotion_price', models.CharField(blank=True, max_length=64, null=True)),
                ('discount', models.CharField(blank=True, max_length=64, null=True)),
                ('moq', models.CharField(blank=True, max_length=128, null=True)),
                ('main_image', models.URLField(blank=True, max_length=1024, null=True)),
                ('review_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('delivery_estimate', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sourcing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sourcing.sourcingrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sourcing.supplier')),
            ],
        ),
    ]
