# Generated by Django 6.0.7 on 2026-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('contato_extraido', 'Contato extraído'), ('contato_wechat_enviado', 'Contato enviado no WeChat'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='novo', max_length=32),
        ),
    ]
