# Generated by Django 6.0.7 on 2026-07-13 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_captcha', 'Aguardando resolução manual de captcha'), ('extraido', 'Extraído'), ('falha', 'Falha')], default='pendente', max_length=24)),
                ('raw_image', models.ImageField(blank=True, null=True, upload_to='contacts/%Y/%m/')),
                ('phone_raw_text', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('wechat', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_extractions', to='sourcing.productlisting')),
            ],
        ),
    ]
