# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactextraction',
            name='company_website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
