# Generated by Django 6.0.7 on 2026-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactextraction_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactextraction',
            name='company_website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
